version:  '3.7'
services:
  datascience-notebook:
      build: .
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
        - ${LOCAL_WORKING_DIR2}:/home/jovyan/work/mars
        - ${LOCAL_DATASETS}:/home/jovyan/work/datasets
        - ${LOCAL_MODULES}:/home/jovyan/work/modules
        - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      command: "start-notebook.sh \
        --NotebookApp.token=''"
      #extra_hosts:
      #  - "mymachine:192.168.2.43"